name: dh_slider
description: A handy slider that supports color and image settings for thumb and track.
version: 1.0.2
homepage: https://github.com/evansherry/dh_slider

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: