name: dh_slider
description: A handy slider that supports color and image settings for thumb and track.
version: 1.0.0
homepage: https://github.com/evansherry/dh_slider

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: